apiVersion: v1
kind: Pod
metadata:
  name: podtest
spec:
  containers:
    - name: excelpoc
      image: docker.io/rishab31/kubsecrets:latest
      envFrom:
        - secretRef:
            name: plaintext-secret
