apiVersion: v1
kind: Pod
metadata:
  name: podtest
spec:
  containers:
  - name: excelpoc
    image: docker.io/rishab31/kubsecrets:latest
    env:
      - name: random
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
