apiVersion: v1
kind: Pod
metadata:
  name: podtest
spec:
  containers:
  - name: mycontainer
    image: docker.io/rishab31/kubsecrets:latest
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: AWS_ACCESS_KEY
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: AWS_SECRET_KEY
  restartPolicy: Never